<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categoryIds = Category::query()->pluck('id', 'name');
        $brandIds = Brand::query()->pluck('id', 'name');

        $products = [
            [
                'category_name' => 'Coffee Machines',
                'brand_name' => 'DeLonghi',
                'name' => 'Royal Professional Coffee Maker',
                'short_description' => 'Fully automatic espresso machine with built-in ceramic grinder, adjustable grind settings, and integrated milk frother for cafe-quality espresso at home.',
                'description' => 'The Saeco Royal Professional is a fully automatic espresso machine designed for coffee lovers who demand complete control over every cup. Its built-in ceramic grinder with adjustable grind settings lets you tailor the coarseness to your preferred beans, while the integrated milk frother delivers velvety microfoam for lattes and cappuccinos at the touch of a button. The large 2.5-litre water tank and spacious bean hopper mean fewer refills during busy mornings. With a robust stainless steel body and intuitive control panel, the Royal Professional combines a professional café experience with the convenience of home brewing.',
                'price' => 899.99,
                'stock_quantity' => 9,
            ],
            [
                'category_name' => 'Laptops',
                'brand_name' => 'Microsoft',
                'name' => 'Surface Go 3',
                'short_description' => 'Compact 2-in-1 with a 10.5-inch PixelSense touchscreen, Intel processor, and Windows 11 - ideal for students and on-the-go professionals.',
                'description' => 'The Microsoft Surface Go 3 is a compact, lightweight 2-in-1 laptop built for students, commuters, and creative professionals who need portability without sacrificing productivity. Its 10.5-inch PixelSense touchscreen delivers sharp, vibrant visuals at 1920x1280 resolution with a 3:2 aspect ratio ideal for reading and writing. Powered by the Intel Pentium Gold 6500Y processor and running Windows 11, it handles everyday tasks, Office apps, and web browsing with ease. At just 544 grams, it slips effortlessly into a backpack, and the all-day battery keeps you going from the first lecture to the last meeting.',
                'price' => 629.99,
                'stock_quantity' => 12,
            ],
            [
                'category_name' => 'Kitchen Appliances',
                'brand_name' => 'Panasonic',
                'name' => 'Microwave Oven',
                'short_description' => '25-litre microwave with Inverter technology for even heating, 900 W output, and a digital touch panel with auto-cook programs for everyday use.',
                'description' => 'The Panasonic Microwave Oven brings intelligent cooking technology into your kitchen with its patented Inverter heating system, which delivers a continuous, consistent power stream instead of the stop-start cycling of traditional microwaves. The result is food that heats evenly from edge to edge, with no overcooked corners or cold centres. Its 25-litre capacity easily accommodates large dinner plates and family-sized portions, while the 900 W power output ensures fast, efficient results across reheating, defrosting, and cooking programs.',
                'price' => 219.99,
                'stock_quantity' => 4,
            ],
            [
                'category_name' => 'Peripherals',
                'brand_name' => 'Microsoft',
                'name' => 'Wireless Mouse M510',
                'short_description' => 'Ergonomic wireless mouse with 24-month battery life, laser tracking on any surface, and a plug-and-forget Unifying nano-receiver.',
                'description' => 'The Logitech Wireless Mouse M510 is engineered for all-day comfort and multi-surface precision. Its sculpted, right-handed contour fits naturally in the hand, reducing wrist fatigue during long work and browsing sessions. The advanced laser sensor tracks reliably on virtually any surface - including glass - without the need for a mouse pad. Two AA batteries power the M510 for up to 24 months, making it one of the most energy-efficient wireless mice available.',
                'price' => 34.99,
                'stock_quantity' => 17,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Apple',
                'name' => 'iPhone 11',
                'short_description' => 'Reliable smartphone with a 6.1-inch Liquid Retina display, A13 Bionic chip, dual 12 MP cameras with Night mode, and IP68 water resistance.',
                'description' => 'The Apple iPhone 11 remains one of the most well-rounded smartphones Apple has released, combining reliable everyday performance with a dual-camera system that punches well above its price. The 6.1-inch Liquid Retina HD display is bright, colour-accurate, and protected by Ceramic Shield glass. Under the hood, the A13 Bionic chip handles demanding apps, games, and video editing with ease, and the Neural Engine powers computational photography features like Portrait mode, Smart HDR, and Night mode.',
                'price' => 479.99,
                'stock_quantity' => 15,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Motorola',
                'name' => 'Razr 50 Ultra',
                'short_description' => 'Premium foldable phone with a 6.9-inch 165Hz display, 4-inch external screen, Snapdragon 8s Gen 3 chip, and dual 50 MP cameras.',
                'description' => 'The Motorola Razr 50 Ultra redefines what a foldable phone can be, pairing a large 4-inch external pOLED display with a flagship-grade 6.9-inch main display running at 165Hz for silky-smooth scrolling. The Snapdragon 8s Gen 3 chipset delivers desktop-class performance in a pocketable form factor. The dual 50 MP camera system produces stunning detail and wide dynamic range.',
                'price' => 999.99,
                'stock_quantity' => 3,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Motorola',
                'name' => 'Moto G86',
                'short_description' => 'Mid-range smartphone with a 6.67-inch 120Hz pOLED display, 50 MP OIS camera, 5000 mAh battery, and 33W TurboPower fast charging.',
                'description' => 'The Motorola Moto G86 is designed for users who want a premium experience at a mid-range price. Its 6.67-inch pOLED display with 120Hz refresh rate makes every swipe and scroll feel fluid. The 50 MP OIS main camera stabilises handheld shots and low-light captures. A 5000 mAh battery with 33W TurboPower charging provides all-day endurance and quick top-ups.',
                'price' => 289.99,
                'stock_quantity' => 8,
            ],
            [
                'category_name' => 'Vacuum Cleaners',
                'brand_name' => 'LG',
                'name' => 'ZB2951 ErgoRapido',
                'short_description' => 'Lightweight cordless 2-in-1 stick vacuum with automatic power boost, up to 30 min runtime, and a detachable handheld unit for versatile cleaning.',
                'description' => 'The Electrolux ZB2951 ErgoRapido is a versatile 2-in-1 cordless vacuum that transforms from a full-size stick vacuum into a compact handheld in seconds. Its Automatic Boost technology detects carpet and instantly increases suction power. Up to 30 minutes of cordless runtime gives you the freedom to clean the whole home on a single charge.',
                'price' => 249.99,
                'stock_quantity' => 11,
            ],
            [
                'category_name' => 'Power',
                'brand_name' => 'Samsung',
                'name' => 'Power Bank 20000 mAh',
                'short_description' => 'High-capacity 20000 mAh power bank with 22.5W fast charging, three simultaneous outputs, and a precise digital battery indicator.',
                'description' => 'The Baseus 20000 mAh Power Bank is the travel companion that keeps all your devices topped up through long journeys, outdoor adventures, and multi-day trips. Its massive 20000 mAh capacity can fully recharge a smartphone four to five times. Two USB-A outputs and a USB-C port allow simultaneous charging of three devices at once.',
                'price' => 49.99,
                'stock_quantity' => 5,
            ],
            [
                'category_name' => 'Refrigerators',
                'brand_name' => 'Bosch',
                'name' => 'Refrigerator',
                'short_description' => 'Energy-efficient top-freezer refrigerator with 268 L capacity, A++ energy rating, adjustable shelves, and whisper-quiet 40 dB operation.',
                'description' => 'The Snaige Refrigerator combines classic reliability with a modern, clean interior design that maximises usable storage space. Its 268-litre total capacity across the fridge and freezer compartments provides ample room for a family\'s weekly shop, while adjustable glass shelves and door bins let you arrange food exactly as you like.',
                'price' => 549.99,
                'stock_quantity' => 2,
            ],
            [
                'category_name' => 'Vacuum Cleaners',
                'brand_name' => 'Dyson',
                'name' => 'Complete C3 Vacuum',
                'short_description' => 'Premium canister vacuum with a powerful Vortex Motor, HEPA AirClean filter, 4.5 L dust bag, 7.5 m cable, and 20-year build quality.',
                'description' => 'The Miele Complete C3 is a premium canister vacuum cleaner that sets the standard for thorough, hygienic home cleaning. Its 890 W Miele-manufactured Vortex Motor generates powerful, consistent suction that lifts deep-seated dust, pet hair, and allergens from carpets, hard floors, and upholstery.',
                'price' => 399.99,
                'stock_quantity' => 7,
            ],
            [
                'category_name' => 'Wearables',
                'brand_name' => 'Apple',
                'name' => 'Watch Series 6',
                'short_description' => 'Feature-rich smartwatch with blood oxygen sensor, ECG app, always-on Retina display, built-in GPS, Apple Pay, and WR50 water resistance.',
                'description' => 'The Apple Watch Series 6 goes beyond timekeeping to become a comprehensive health and fitness companion worn on your wrist. The blood oxygen sensor and ECG app provide meaningful health insights you can share with your doctor, while the optical heart rate sensor tracks your heart rate continuously throughout the day.',
                'price' => 299.99,
                'stock_quantity' => 6,
            ],
            [
                'category_name' => 'Power',
                'brand_name' => 'Molicel',
                'name' => '8S3P Molicel Battery Pack',
                'short_description' => 'High-capacity battery pack for demanding power storage setups and off-grid backup systems.',
                'description' => 'The 8S3P Molicel Battery Pack is built for users who need dependable energy storage in a compact module. Its high-discharge cells are suited to backup power projects, renewable energy setups, and other demanding applications where stability matters. The pack is designed to deliver consistent performance with a practical layout for installation and maintenance.',
                'price' => 699.99,
                'stock_quantity' => 3,
            ],
            [
                'category_name' => 'Power',
                'brand_name' => 'Deye',
                'name' => 'SE-G5.1 Pro-B Battery',
                'short_description' => 'Modular lithium battery for solar and home energy storage systems.',
                'description' => 'The Deye SE-G5.1 Pro-B Battery is a modular storage solution designed for solar installations and backup power systems. It offers a scalable approach to residential energy storage, helping smooth out consumption during peak demand or outages. The compact form factor makes it easy to integrate into an existing power setup.',
                'price' => 1299.99,
                'stock_quantity' => 4,
            ],
            [
                'category_name' => 'Power',
                'brand_name' => 'Langzeit',
                'name' => 'Langzeit Battery Pack',
                'short_description' => 'Long-life battery pack designed for reliable backup and extended runtime.',
                'description' => 'The Langzeit Battery Pack focuses on longevity and stable output for everyday backup power needs. It is suited to home and workshop environments where dependable runtime is more important than flashy specs. The durable enclosure and practical format make it a straightforward storage option for repeat use.',
                'price' => 459.99,
                'stock_quantity' => 5,
            ],
            [
                'category_name' => 'PC Components',
                'brand_name' => null,
                'name' => 'USB 2.0 Cable',
                'short_description' => 'Simple USB 2.0 cable for data transfer and everyday device charging.',
                'description' => 'The USB 2.0 Cable is a dependable everyday accessory for connecting peripherals, charging compatible devices, and handling standard data transfers. Its flexible build makes it easy to route through desks, entertainment setups, and accessory kits without clutter.',
                'price' => 9.99,
                'stock_quantity' => 48,
            ],
            [
                'category_name' => 'Cameras',
                'brand_name' => 'Canon',
                'name' => 'EOS R100',
                'short_description' => 'Entry-level mirrorless camera with fast autofocus and an easy-to-use control layout.',
                'description' => 'The Canon EOS R100 is a lightweight mirrorless camera built for first-time creators and casual photographers who want better image quality without a steep learning curve. It combines Canon’s familiar handling with modern autofocus and strong still-photo performance in a compact body.',
                'price' => 579.99,
                'stock_quantity' => 7,
            ],
            [
                'category_name' => 'Cameras',
                'brand_name' => 'Insta360',
                'name' => 'X5',
                'short_description' => 'Versatile action camera with 360-degree capture and stabilized video recording.',
                'description' => 'The Insta360 X5 is made for creators who want flexible shooting modes in a compact body. It captures immersive 360-degree footage and uses advanced stabilisation to keep handheld clips smooth during fast movement. The camera is a strong fit for travel, action sports, and social-first content creation.',
                'price' => 649.99,
                'stock_quantity' => 4,
            ],
            [
                'category_name' => 'Cameras',
                'brand_name' => 'Samsung',
                'name' => 'DV150F',
                'short_description' => 'Compact digital camera with front display and simple wireless sharing features.',
                'description' => 'The Samsung DV150F is a compact camera that focuses on portability and convenience. Its lightweight design makes it easy to carry every day, while the front-facing display helps with framing selfies and casual shots. It is a practical option for users who want a dedicated camera for simple photo capture.',
                'price' => 179.99,
                'stock_quantity' => 6,
            ],
            [
                'category_name' => 'Air Conditioners',
                'brand_name' => 'Osaka',
                'name' => 'Air Conditioner',
                'short_description' => 'Efficient air conditioner designed to keep rooms cool and comfortable.',
                'description' => 'The Osaka Air Conditioner is a straightforward cooling solution for home or office use. It is designed to provide reliable temperature control with everyday operation in mind, helping maintain a comfortable indoor environment during hot weather.',
                'price' => 429.99,
                'stock_quantity' => 2,
            ],
            [
                'category_name' => 'TV & Displays',
                'brand_name' => 'Apple',
                'name' => 'Studio Display',
                'short_description' => 'High-resolution monitor with sharp visuals and a clean all-metal design.',
                'description' => 'The Apple Studio Display delivers a polished viewing experience with crisp image quality and a premium aluminium enclosure. It is aimed at users who want a refined external display for creative work, productivity, and everyday desktop use.',
                'price' => 1599.99,
                'stock_quantity' => 2,
            ],
            [
                'category_name' => 'Headphones',
                'brand_name' => 'Apple',
                'name' => 'AirPods 3',
                'short_description' => 'Wireless earbuds with spatial audio support and a comfortable open-fit design.',
                'description' => 'AirPods 3 provide a familiar Apple wireless earbud experience with an open-fit design that is easy to wear throughout the day. They are suited to calls, music, and quick media playback, with seamless pairing across Apple devices.',
                'price' => 179.99,
                'stock_quantity' => 10,
            ],
            [
                'category_name' => 'Headphones',
                'brand_name' => 'JLab',
                'name' => 'JLab Earbuds',
                'short_description' => 'Compact wireless earbuds for everyday listening and portable use.',
                'description' => 'JLab Earbuds are built for users who want a simple and affordable wireless audio option. They focus on convenience, portability, and quick access to music or calls while keeping the design small enough for travel and daily carry.',
                'price' => 39.99,
                'stock_quantity' => 18,
            ],
            [
                'category_name' => 'Gaming',
                'brand_name' => 'Sony',
                'name' => 'PlayStation 4 Fat',
                'short_description' => 'Original PS4 console with a familiar chassis and access to a huge game library.',
                'description' => 'The PlayStation 4 Fat is the original PS4 design that introduced Sony’s eighth-generation console ecosystem to millions of players. It remains a solid choice for access to a large library of games, media apps, and local multiplayer entertainment.',
                'price' => 249.99,
                'stock_quantity' => 5,
            ],
            [
                'category_name' => 'Gaming',
                'brand_name' => 'Sony',
                'name' => 'PlayStation 4 Pro',
                'short_description' => 'Enhanced PS4 model with improved performance for higher-resolution gaming.',
                'description' => 'The PlayStation 4 Pro delivers a stronger gaming experience than the original PS4, with extra horsepower for sharper visuals and smoother frame rates in supported titles. It is a good fit for players who want to extend the life of the PS4 ecosystem with upgraded performance.',
                'price' => 299.99,
                'stock_quantity' => 4,
            ],
            [
                'category_name' => 'PC Components',
                'brand_name' => 'Cooler Master',
                'name' => 'Silent Pro M2 Power Supply',
                'short_description' => 'Quiet power supply unit for stable desktop builds and reliable everyday use.',
                'description' => 'The Cooler Master Silent Pro M2 Power Supply is aimed at builders who want dependable output and low-noise operation. It is designed to support stable PC builds while keeping acoustic output under control, making it a practical choice for workstations and home desktops.',
                'price' => 119.99,
                'stock_quantity' => 6,
            ],
            [
                'category_name' => 'PC Components',
                'brand_name' => 'Raidmax',
                'name' => 'Cobra Power Supply',
                'short_description' => 'Affordable desktop power supply for practical PC builds.',
                'description' => 'The Raidmax Cobra Power Supply is a budget-friendly option for everyday desktop systems. It focuses on providing the essentials needed for a stable build without unnecessary extras, making it suitable for basic home and office setups.',
                'price' => 69.99,
                'stock_quantity' => 8,
            ],
            [
                'category_name' => 'Speakers',
                'brand_name' => 'Tronsmart',
                'name' => 'Bang SE',
                'short_description' => 'Portable Bluetooth speaker with punchy sound and party-ready battery life.',
                'description' => 'The Tronsmart Bang SE is a portable speaker built for outdoor listening, casual gatherings, and travel. It focuses on bold sound, easy wireless connectivity, and a rugged enough design to move between rooms or take on the road.',
                'price' => 89.99,
                'stock_quantity' => 7,
            ],
            [
                'category_name' => 'Tablets',
                'brand_name' => 'Apple',
                'name' => 'iPad 9',
                'short_description' => 'Classic iPad with a familiar design and dependable everyday performance.',
                'description' => 'The Apple iPad 9 is a versatile tablet for browsing, streaming, note-taking, and light productivity. It keeps the traditional iPad form factor and offers a dependable experience for users who want a simple tablet that handles everyday tasks with ease.',
                'price' => 329.99,
                'stock_quantity' => 9,
            ],
            [
                'category_name' => 'Tablets',
                'brand_name' => 'Samsung',
                'name' => 'Galaxy Tab S11',
                'short_description' => 'Premium Android tablet with a large display and multitasking-friendly performance.',
                'description' => 'The Samsung Galaxy Tab S11 is positioned as a premium Android tablet for productivity, media, and entertainment. Its large display and responsive performance make it a strong choice for users who want a more capable tablet experience.',
                'price' => 899.99,
                'stock_quantity' => 4,
            ],
            [
                'category_name' => 'Tablets',
                'brand_name' => 'Wacom',
                'name' => 'Intuos Pro Large',
                'short_description' => 'Professional drawing tablet for digital artists and designers.',
                'description' => 'The Wacom Intuos Pro Large is a pen tablet designed for illustration, photo editing, and design work. Its large active area gives artists more room to sketch naturally, while the pen input is tailored to precise creative workflows.',
                'price' => 379.99,
                'stock_quantity' => 5,
            ],
            [
                'category_name' => 'Washing Machines',
                'brand_name' => 'Bosch',
                'name' => 'WAN282ECO',
                'short_description' => 'Efficient front-loading washing machine for dependable family laundry care.',
                'description' => 'The Bosch WAN282ECO is a practical washing machine built for everyday household laundry. It focuses on efficient cleaning, sensible program choices, and reliable long-term use, making it a straightforward fit for regular home routines.',
                'price' => 649.99,
                'stock_quantity' => 3,
            ],
            [
                'category_name' => 'Washing Machines',
                'brand_name' => 'Indesit',
                'name' => 'Washing Machine',
                'short_description' => 'Simple household washing machine for regular laundry loads.',
                'description' => 'The Indesit Washing Machine provides a no-fuss approach to daily laundry. It is aimed at households that want a dependable appliance with the core programs needed for routine washing tasks.',
                'price' => 399.99,
                'stock_quantity' => 4,
            ],
            [
                'category_name' => 'Washing Machines',
                'brand_name' => 'Zanussi',
                'name' => 'ZWT5105',
                'short_description' => 'Compact top-loading washing machine for practical home use.',
                'description' => 'The Zanussi ZWT5105 is a compact washing machine suited to homes that need a space-conscious laundry appliance. It combines a simple control layout with the essential wash programs needed for everyday clothing care.',
                'price' => 349.99,
                'stock_quantity' => 2,
            ],
            [
                'category_name' => 'Coffee Machines',
                'brand_name' => 'La Marzocco',
                'name' => 'Linea Mini',
                'short_description' => 'Professional espresso machine for home baristas seeking cafe-quality performance.',
                'description' => 'The La Marzocco Linea Mini brings professional espresso machine engineering into the home. With precise temperature control, group stability, and ergonomic steam wands, it delivers the consistency and control that espresso enthusiasts demand. The compact footprint fits modern kitchen counters while maintaining the quality standards of commercial machines.',
                'price' => 3299.99,
                'stock_quantity' => 2,
            ],
            [
                'category_name' => 'Coffee Machines',
                'brand_name' => 'Profi Cook',
                'name' => 'PC-KA 1191',
                'short_description' => 'Compact automatic coffee machine with integrated grinder and froth function.',
                'description' => 'The Profi Cook PC-KA 1191 is a user-friendly automatic espresso machine designed for daily coffee enjoyment. It features an integrated grinder with adjustable fineness, one-touch froth control for milk-based drinks, and a compact design suited to smaller kitchens.',
                'price' => 299.99,
                'stock_quantity' => 5,
            ],
            [
                'category_name' => 'Laptops',
                'brand_name' => 'ASUS',
                'name' => 'ROG Zephyrus G15',
                'short_description' => 'High-performance gaming laptop with RTX graphics, 240Hz display, and advanced cooling.',
                'description' => 'The ASUS ROG Zephyrus G15 is a premium gaming laptop built for serious gamers and creators. Its powerful GPU delivers smooth frame rates in demanding games, while the 240Hz display ensures ultra-responsive visuals. Advanced cooling keeps performance stable during long sessions.',
                'price' => 2499.99,
                'stock_quantity' => 3,
            ],
            [
                'category_name' => 'Laptops',
                'brand_name' => 'HP',
                'name' => 'Ryzen 5 Laptop',
                'short_description' => 'Mid-range laptop with AMD Ryzen 5 processor for everyday tasks and light gaming.',
                'description' => 'The HP Ryzen 5 Laptop offers a balanced mix of performance and value. Its AMD Ryzen 5 processor handles multitasking smoothly, and integrated graphics support casual gaming and content creation. The modern design and responsive keyboard make it suitable for work and entertainment.',
                'price' => 649.99,
                'stock_quantity' => 8,
            ],
            [
                'category_name' => 'Laptops',
                'brand_name' => 'Lenovo',
                'name' => 'ThinkPad T14s Gen 2',
                'short_description' => 'Business-class ultrabook with security features, long battery life, and premium build quality.',
                'description' => 'The Lenovo ThinkPad T14s Gen 2 is a professional ultrabook designed for demanding work environments. Its sturdy construction, excellent keyboard, comprehensive security features, and all-day battery make it the choice of business users who value reliability and productivity.',
                'price' => 1299.99,
                'stock_quantity' => 4,
            ],
            [
                'category_name' => 'Laptops',
                'brand_name' => 'Apple',
                'name' => 'MacBook Pro 15',
                'short_description' => 'Premium laptop with M-series chip, Retina display, and professional-grade performance.',
                'description' => 'The Apple MacBook Pro 15 combines powerful Apple silicon with a stunning Retina display and premium build. It is optimized for creative professionals who need consistent performance for video editing, 3D rendering, and other demanding workflows.',
                'price' => 2399.99,
                'stock_quantity' => 3,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Apple',
                'name' => 'iPhone 11 Pro Max',
                'short_description' => 'Flagship iPhone with triple camera system, larger display, and all-day battery.',
                'description' => 'The Apple iPhone 11 Pro Max is a flagship smartphone with a larger 6.5-inch display and a professional triple-camera system. Night mode, ProRaw support, and a stainless steel design make it the choice of photographers and power users.',
                'price' => 749.99,
                'stock_quantity' => 6,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Apple',
                'name' => 'iPhone 12',
                'short_description' => 'Modern iPhone with 5G, dual cameras, flat edges, and ceramic shield screen.',
                'description' => 'The Apple iPhone 12 introduces 5G connectivity, an improved dual-camera system, and a refined design with flat edges. Ceramic Shield provides superior drop protection while maintaining a familiar iPhone experience.',
                'price' => 599.99,
                'stock_quantity' => 8,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Apple',
                'name' => 'iPhone 13',
                'short_description' => 'Advanced iPhone with improved camera performance, faster chip, and longer battery life.',
                'description' => 'The Apple iPhone 13 improves on its predecessor with faster performance, a better dual-camera system, and improved battery endurance. Cinematic mode for video adds creative possibilities for mobile filming.',
                'price' => 699.99,
                'stock_quantity' => 7,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Apple',
                'name' => 'iPhone 15 Pro',
                'short_description' => 'Latest flagship iPhone with advanced camera features, titanium design, and powerful processor.',
                'description' => 'The Apple iPhone 15 Pro combines titanium construction with advanced computational photography. Its pro-grade camera system and powerful processor make it suitable for photography enthusiasts and power users.',
                'price' => 999.99,
                'stock_quantity' => 5,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Apple',
                'name' => 'iPhone 16 Pro',
                'short_description' => 'Next-generation flagship with cutting-edge features and premium build quality.',
                'description' => 'The Apple iPhone 16 Pro represents the latest in smartphone technology with advanced features, premium materials, and exceptional performance for demanding users.',
                'price' => 1099.99,
                'stock_quantity' => 4,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Apple',
                'name' => 'iPhone 7 Plus',
                'short_description' => 'Older flagship model with dual cameras, larger display, and reliable performance.',
                'description' => 'The Apple iPhone 7 Plus is an older flagship that still delivers solid performance. Its dual-camera system and larger 5.5-inch display made it popular among users seeking photography capabilities.',
                'price' => 399.99,
                'stock_quantity' => 0,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Apple',
                'name' => 'iPhone X',
                'short_description' => 'Iconic iPhone with notch design, Face ID, and dual cameras.',
                'description' => 'The Apple iPhone X introduced the notch design and Face ID facial recognition to the iPhone lineup. It remains a capable device for everyday use and photography.',
                'price' => 599.99,
                'stock_quantity' => 0,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'General Mobile',
                'name' => 'GM 8 Go',
                'short_description' => 'Budget smartphone with clean Android experience and adequate everyday performance.',
                'description' => 'The General Mobile GM 8 Go is a budget-friendly Android phone designed for users seeking basic smartphone functionality. Its clean Android experience and straightforward design make it suitable for first-time smartphone users.',
                'price' => 129.99,
                'stock_quantity' => 10,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Samsung',
                'name' => 'Galaxy M22',
                'short_description' => 'Mid-range Android phone with 90Hz display and long battery life.',
                'description' => 'The Samsung Galaxy M22 offers a good balance of features and price. Its 90Hz display provides smooth scrolling, and the large 5000 mAh battery delivers exceptional endurance.',
                'price' => 249.99,
                'stock_quantity' => 7,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Samsung',
                'name' => 'Galaxy S23 FE',
                'short_description' => 'Fan-edition Samsung flagship with excellent camera and performance at a lower price.',
                'description' => 'The Samsung Galaxy S23 FE delivers flagship features at a more accessible price point. Its strong camera system, smooth performance, and reliable battery make it a solid choice for Android users.',
                'price' => 699.99,
                'stock_quantity' => 6,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Samsung',
                'name' => 'Galaxy S24',
                'short_description' => 'Latest Samsung flagship with advanced AI features and premium performance.',
                'description' => 'The Samsung Galaxy S24 is the latest flagship phone featuring advanced AI enhancements, premium build quality, and exceptional camera performance for photography enthusiasts.',
                'price' => 899.99,
                'stock_quantity' => 5,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Samsung',
                'name' => 'Galaxy Z Fold',
                'short_description' => 'Premium foldable phone with expansive screen and powerful performance.',
                'description' => 'The Samsung Galaxy Z Fold is a premium foldable smartphone that transforms from a compact phone into a tablet-sized screen. Its innovative design and powerful internals make it a statement device for tech enthusiasts.',
                'price' => 1799.99,
                'stock_quantity' => 0,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Sony',
                'name' => 'Xperia XA2 Ultra',
                'short_description' => 'Sony flagship with dual front cameras and compact bezels for immersive viewing.',
                'description' => 'The Sony Xperia XA2 Ultra is a mid-range Sony phone featuring dual front cameras for selfies, a compact design, and reliable performance suitable for everyday use.',
                'price' => 399.99,
                'stock_quantity' => 4,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Xiaomi',
                'name' => 'Redmi A5',
                'short_description' => 'Budget Android phone with clean software and reliable performance.',
                'description' => 'The Xiaomi Redmi A5 is an entry-level Android phone that focuses on simplicity and reliability. Its clean MIUI interface and affordable price make it accessible to budget-conscious users.',
                'price' => 149.99,
                'stock_quantity' => 0,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Xiaomi',
                'name' => 'Redmi 9A',
                'short_description' => 'Entry-level smartphone with a large display, dependable battery life, and smooth daily performance.',
                'description' => 'The Xiaomi Redmi 9A is built for users who want a reliable smartphone for calls, messaging, social apps, and media playback without stretching their budget. Its large display makes browsing and video watching comfortable, while the efficient chipset and long-lasting battery provide stable day-to-day use.',
                'price' => 139.99,
                'stock_quantity' => 8,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Xiaomi',
                'name' => 'Redmi Note 13',
                'short_description' => 'Modern mid-range phone with AMOLED display, capable camera system, and fast charging support.',
                'description' => 'The Xiaomi Redmi Note 13 offers a balanced mix of performance and value for users who want a premium-feeling experience at a mid-range price. Its vivid display, responsive performance, and strong battery life make it a practical daily driver for productivity, entertainment, and mobile photography.',
                'price' => 329.99,
                'stock_quantity' => 3,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Xiaomi',
                'name' => 'Redmi Note 8T',
                'short_description' => 'Affordable Redmi model with solid all-around performance and practical camera features.',
                'description' => 'The Xiaomi Redmi Note 8T is a dependable smartphone focused on practical everyday use. It combines good battery endurance, smooth navigation for common apps, and versatile camera options, making it a strong choice for users who need reliable performance at an accessible cost.',
                'price' => 199.99,
                'stock_quantity' => 7,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Samsung',
                'name' => 'Galaxy A52',
                'short_description' => 'Popular Samsung mid-range phone with AMOLED screen, OIS camera, and excellent everyday usability.',
                'description' => 'The Samsung Galaxy A52 is a well-rounded mid-range smartphone designed for users who want premium essentials without flagship pricing. Its bright AMOLED display, stabilized main camera, and balanced software experience make it suitable for photography, social media, work, and entertainment.',
                'price' => 379.99,
                'stock_quantity' => 4,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Samsung',
                'name' => 'Galaxy S21',
                'short_description' => 'Compact Samsung flagship with high-end performance, great cameras, and premium build quality.',
                'description' => 'The Samsung Galaxy S21 delivers flagship-grade performance in a comfortable form factor. It features a high-refresh-rate display, a versatile camera system, and strong processing power that handles multitasking, gaming, and content creation with ease.',
                'price' => 649.99,
                'stock_quantity' => 0,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Xiaomi',
                'name' => 'Xiaomi 11T',
                'short_description' => 'Performance-focused smartphone with fast display, rapid charging, and strong multimedia experience.',
                'description' => 'The Xiaomi 11T is built for speed and media consumption, combining a smooth high-refresh display with powerful internals and fast charging for minimal downtime. It is a great fit for users who stream often, play games, and want responsive performance throughout the day.',
                'price' => 469.99,
                'stock_quantity' => 5,
            ],
            [
                'category_name' => 'Phones',
                'brand_name' => 'Xiaomi',
                'name' => 'Xiaomi Redmi 9',
                'short_description' => 'Budget-friendly Redmi device with large battery and balanced performance for daily tasks.',
                'description' => 'The Xiaomi Redmi 9 offers dependable entry-level performance for users who need a straightforward Android experience. With a long-lasting battery and practical hardware, it handles communication, browsing, and everyday apps reliably.',
                'price' => 169.99,
                'stock_quantity' => 0,
            ],
            [
                'category_name' => 'Vacuum Cleaners',
                'brand_name' => 'Bissell',
                'name' => 'Crosswave Select C3 3551N',
                'short_description' => 'Multi-surface wet and dry vacuum for carpets, hard floors, and rugs.',
                'description' => 'The Bissell Crosswave Select C3 is a versatile multi-surface cleaner that handles both wet and dry messes. Its dual-tank system keeps clean and dirty water separate, making it ideal for households with mixed flooring.',
                'price' => 449.99,
                'stock_quantity' => 3,
            ],
            [
                'category_name' => 'Vacuum Cleaners',
                'brand_name' => 'Ecovacs',
                'name' => 'DEEBOT T10 Plus Ozmo',
                'short_description' => 'Robot vacuum with moping capability and intelligent navigation for automated cleaning.',
                'description' => 'The Ecovacs DEEBOT T10 Plus Ozmo is a robot vacuum that combines vacuuming with wet mopping. Its intelligent navigation and app control make it convenient for hands-off home cleaning.',
                'price' => 699.99,
                'stock_quantity' => 4,
            ],
            [
                'category_name' => 'Vacuum Cleaners',
                'brand_name' => 'Roborock',
                'name' => 'S5 Max',
                'short_description' => 'Advanced robot vacuum with mapping, scheduling, and large dustbin capacity.',
                'description' => 'The Roborock S5 Max is a capable robot vacuum with advanced mapping technology, scheduled cleaning, and a large dustbin. Its efficient cleaning patterns and smart app control make it a reliable choice for automated vacuuming.',
                'price' => 799.99,
                'stock_quantity' => 3,
            ],
            [
                'category_name' => 'Vacuum Cleaners',
                'brand_name' => 'Rowenta',
                'name' => 'X-Force Flex',
                'short_description' => 'Lightweight cordless stick vacuum with flexible stick design and strong suction.',
                'description' => 'The Rowenta X-Force Flex is a cordless stick vacuum featuring a flexible stick that bends for cleaning under furniture. Its lightweight design and strong suction make it convenient for everyday cleaning tasks.',
                'price' => 549.99,
                'stock_quantity' => 4,
            ],
            [
                'category_name' => 'Vacuum Cleaners',
                'brand_name' => 'Rowenta',
                'name' => 'X-Plorer Serie 75S',
                'short_description' => 'Cordless vacuum with advanced air flow technology and adjustable suction levels.',
                'description' => 'The Rowenta X-Plorer Serie 75S is a premium cordless vacuum with multiple power modes and advanced filtration. Its long runtime and lightweight design make it suitable for comprehensive home cleaning.',
                'price' => 599.99,
                'stock_quantity' => 3,
            ],
            [
                'category_name' => 'Vacuum Cleaners',
                'brand_name' => 'Xiaomi',
                'name' => 'Vacuum S20',
                'short_description' => 'Robot vacuum with smart mapping and efficient cleaning patterns.',
                'description' => 'The Xiaomi Vacuum S20 is an affordable robot vacuum with basic smart features and reliable cleaning performance. Its compact design fits well under furniture while maintaining adequate dust capacity.',
                'price' => 399.99,
                'stock_quantity' => 5,
            ],
            [
                'category_name' => 'Vacuum Cleaners',
                'brand_name' => 'ZooZee',
                'name' => 'Z70 Robot Vacuum',
                'short_description' => 'Budget-friendly robot vacuum with basic automation and quiet operation.',
                'description' => 'The ZooZee Z70 is a budget robot vacuum that offers basic automation for everyday cleaning. Its quiet operation and simple scheduling make it a practical choice for cost-conscious users.',
                'price' => 299.99,
                'stock_quantity' => 4,
            ],
            [
                'category_name' => 'Wearables',
                'brand_name' => 'Garmin',
                'name' => 'Vivoactive 6',
                'short_description' => 'Fitness smartwatch with health tracking, sports modes, and long battery life.',
                'description' => 'The Garmin Vivoactive 6 is a fitness-focused smartwatch designed for active users. With comprehensive health metrics, diverse sports tracking modes, and multi-day battery life, it is ideal for fitness enthusiasts and outdoor adventurers.',
                'price' => 449.99,
                'stock_quantity' => 5,
            ],
        ];

        foreach ($products as $data) {
            $categoryId = $categoryIds[$data['category_name']] ?? null;
            $brandId = $brandIds[$data['brand_name']] ?? null;

            Product::query()->firstOrCreate(
                ['name' => $data['name']],
                [
                    'category_id' => $categoryId,
                    'brand_id' => $brandId,
                    'short_description' => $data['short_description'],
                    'description' => $data['description'],
                    'price' => $data['price'],
                    'stock_quantity' => $data['stock_quantity'],
                ]
            );
        }
    }
}
