<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categoryIds = Category::query()->pluck('id', 'slug');

        $products = [
            ['slug' => 'saeco-royal-professional', 'category_slug' => 'home-appliances', 'brand' => 'Saeco', 'name' => 'Royal Professional Coffee Maker', 'short_description' => 'Fully automatic espresso machine with built-in ceramic grinder, adjustable grind settings, and integrated milk frother for café-quality espresso at home.', 'description' => 'The Saeco Royal Professional is a fully automatic espresso machine designed for coffee lovers who demand complete control over every cup. Its built-in ceramic grinder with adjustable grind settings lets you tailor the coarseness to your preferred beans, while the integrated milk frother delivers velvety microfoam for lattes and cappuccinos at the touch of a button. The large 2.5-litre water tank and spacious bean hopper mean fewer refills during busy mornings. With a robust stainless steel body and intuitive control panel, the Royal Professional combines a professional café experience with the convenience of home brewing.', 'price' => 899.99, 'sort_order' => 10, 'popularity_score' => 55, 'stock_left' => 9],
            ['slug' => 'microsoft-surface-go-3', 'category_slug' => 'laptops', 'brand' => 'Microsoft', 'name' => 'Surface Go 3', 'short_description' => 'Compact 2-in-1 with a 10.5-inch PixelSense touchscreen, Intel processor, and Windows 11 — ideal for students and on-the-go professionals.', 'description' => 'The Microsoft Surface Go 3 is a compact, lightweight 2-in-1 laptop built for students, commuters, and creative professionals who need portability without sacrificing productivity. Its 10.5-inch PixelSense touchscreen delivers sharp, vibrant visuals at 1920×1280 resolution with a 3:2 aspect ratio ideal for reading and writing. Powered by the Intel Pentium Gold 6500Y processor and running Windows 11, it handles everyday tasks, Office apps, and web browsing with ease. The precision keyboard and Surface Pen support make note-taking and sketching natural. At just 544 grams, it slips effortlessly into a backpack, and the all-day battery keeps you going from the first lecture to the last meeting.', 'price' => 629.99, 'sort_order' => 20, 'popularity_score' => 72, 'stock_left' => 12],
            ['slug' => 'panasonic-microwave-oven', 'category_slug' => 'home-appliances', 'brand' => 'Panasonic', 'name' => 'Microwave Oven', 'short_description' => '25-litre microwave with Inverter technology for even heating, 900 W output, and a digital touch panel with auto-cook programs for everyday use.', 'description' => 'The Panasonic Microwave Oven brings intelligent cooking technology into your kitchen with its patented Inverter heating system, which delivers a continuous, consistent power stream instead of the stop-start cycling of traditional microwaves. The result is food that heats evenly from edge to edge, with no overcooked corners or cold centres. Its 25-litre capacity easily accommodates large dinner plates and family-sized portions, while the 900 W power output ensures fast, efficient results across reheating, defrosting, and cooking programs. A turntable-free flat floor design makes cleaning simple, and the intuitive digital touch panel guides you through auto-cook menus for popular dishes with minimal effort.', 'price' => 219.99, 'sort_order' => 30, 'popularity_score' => 43, 'stock_left' => 4],
            ['slug' => 'logitech-m510', 'category_slug' => 'accessories', 'brand' => 'Logitech', 'name' => 'Wireless Mouse M510', 'short_description' => 'Ergonomic wireless mouse with 24-month battery life, laser tracking on any surface, and a plug-and-forget Unifying nano-receiver.', 'description' => 'The Logitech Wireless Mouse M510 is engineered for all-day comfort and multi-surface precision. Its sculpted, right-handed contour fits naturally in the hand, reducing wrist fatigue during long work and browsing sessions. The advanced laser sensor tracks reliably on virtually any surface — including glass — without the need for a mouse pad. A plug-and-forget Unifying nano-receiver lets you connect wirelessly without losing the tiny adapter between uses. Two AA batteries power the M510 for up to 24 months, making it one of the most energy-efficient wireless mice available. Seven programmable buttons, including back/forward controls and a hyper-fast scroll wheel, keep everything close at hand.', 'price' => 34.99, 'sort_order' => 40, 'popularity_score' => 86, 'stock_left' => 17],
            ['slug' => 'iphone-11', 'category_slug' => 'smartphones', 'brand' => 'Apple', 'name' => 'iPhone 11', 'short_description' => 'Reliable smartphone with a 6.1-inch Liquid Retina display, A13 Bionic chip, dual 12 MP cameras with Night mode, and IP68 water resistance.', 'description' => 'The Apple iPhone 11 remains one of the most well-rounded smartphones Apple has released, combining reliable everyday performance with a dual-camera system that punches well above its price. The 6.1-inch Liquid Retina HD display is bright, colour-accurate, and protected by Ceramic Shield glass — four times tougher than previous generations. Under the hood, the A13 Bionic chip handles demanding apps, games, and video editing with ease, and the Neural Engine powers computational photography features like Portrait mode, Smart HDR, and Night mode. Splash, water, and dust resistance rated IP68 means it can survive accidental drops in puddles, and the long-lasting battery easily sees through a full day of heavy use.', 'price' => 479.99, 'sort_order' => 50, 'popularity_score' => 95, 'stock_left' => 0],
            ['slug' => 'motorola-razr-50-ultra', 'category_slug' => 'smartphones', 'brand' => 'Motorola', 'name' => 'Razr 50 Ultra', 'short_description' => 'Premium foldable phone with a 6.9-inch 165Hz display, 4-inch external screen, Snapdragon 8s Gen 3 chip, and dual 50 MP cameras.', 'description' => 'The Motorola Razr 50 Ultra redefines what a foldable phone can be, pairing a large 4-inch external pOLED display — the biggest cover screen in its class — with a flagship-grade 6.9-inch main display running at 165Hz for silky-smooth scrolling. The Snapdragon 8s Gen 3 chipset delivers desktop-class performance in a pocketable form factor, handling everything from console-quality gaming to 4K video recording without breaking a sweat. The dual 50 MP camera system produces stunning detail and wide dynamic range, with Motorola\'s AI scene optimisation ensuring great shots in any lighting. When folded, the compact shell fits in the smallest pockets and clutches, making it the ultimate choice for those who refuse to compromise on either style or power.', 'price' => 999.99, 'sort_order' => 60, 'popularity_score' => 67, 'stock_left' => 3],
            ['slug' => 'motorola-g86', 'category_slug' => 'smartphones', 'brand' => 'Motorola', 'name' => 'Moto G86', 'short_description' => 'Mid-range smartphone with a 6.67-inch 120Hz pOLED display, 50 MP OIS camera, 5000 mAh battery, and 33W TurboPower fast charging.', 'description' => 'The Motorola Moto G86 is designed for users who want a premium experience at a mid-range price. Its 6.67-inch pOLED display with 120Hz refresh rate makes every swipe and scroll feel fluid, while deep blacks and vivid colours bring photos, videos, and games to life. The 50 MP OIS main camera stabilises handheld shots and low-light captures, so you get clear, crisp photos even in challenging conditions. A 5000 mAh battery with 33W TurboPower charging provides all-day endurance and quick top-ups when you need them. With a water-resistant design, stereo speakers, and a clean near-stock Android experience, the Moto G86 is a sensible everyday companion that doesn\'t cut corners where it counts.', 'price' => 289.99, 'sort_order' => 70, 'popularity_score' => 58, 'stock_left' => 8],
            ['slug' => 'electrolux-zb-2951', 'category_slug' => 'home-appliances', 'brand' => 'Electrolux', 'name' => 'ZB2951 ErgoRapido', 'short_description' => 'Lightweight cordless 2-in-1 stick vacuum with automatic power boost, up to 30 min runtime, and a detachable handheld unit for versatile cleaning.', 'description' => 'The Electrolux ZB2951 ErgoRapido is a versatile 2-in-1 cordless vacuum that transforms from a full-size stick vacuum into a compact handheld in seconds — simply detach the handheld unit to tackle stairs, upholstery, and car interiors with ease. Its Automatic Boost technology detects carpet and instantly increases suction power, then reduces it on hard floors to conserve battery. Up to 30 minutes of cordless runtime gives you the freedom to clean the whole home on a single charge. The slim swivel nozzle glides effortlessly around chair legs and under furniture, and the washable filter keeps running costs low. Lightweight at under 1.5 kg, the ErgoRapido stores neatly on its charging wall mount, always ready for quick everyday cleanups.', 'price' => 249.99, 'sort_order' => 115, 'popularity_score' => 53, 'stock_left' => 11],
            ['slug' => 'power-bank-20000', 'category_slug' => 'power-batteries', 'brand' => 'Baseus', 'name' => 'Power Bank 20000 mAh', 'short_description' => 'High-capacity 20000 mAh power bank with 22.5W fast charging, three simultaneous outputs, and a precise digital battery indicator.', 'description' => 'The Baseus 20000 mAh Power Bank is the travel companion that keeps all your devices topped up through long journeys, outdoor adventures, and multi-day trips. Its massive 20000 mAh capacity can fully recharge a smartphone four to five times or keep a tablet running for an entire day. Two USB-A outputs and a USB-C port allow simultaneous charging of three devices at once, so your phone, earbuds, and smartwatch can all charge together. The 22.5W fast-charging support significantly cuts down charging times compared to standard power banks, and the built-in digital display shows exact battery percentage so you always know how much power you have left. Compact enough for a jacket pocket, yet powerful enough to handle every device you carry.', 'price' => 49.99, 'sort_order' => 90, 'popularity_score' => 48, 'stock_left' => 5],
            ['slug' => 'snaige-refrigerator', 'category_slug' => 'home-appliances', 'brand' => 'Snaige', 'name' => 'Refrigerator', 'short_description' => 'Energy-efficient top-freezer refrigerator with 268 L capacity, A++ energy rating, adjustable shelves, and whisper-quiet 40 dB operation.', 'description' => 'The Snaige Refrigerator combines classic reliability with a modern, clean interior design that maximises usable storage space. Its 268-litre total capacity across the fridge and freezer compartments provides ample room for a family\'s weekly shop, while adjustable glass shelves and door bins let you arrange food exactly as you like. An A++ energy rating keeps electricity costs low over years of daily use, and whisper-quiet 40 dB operation ensures it never disturbs a peaceful kitchen. The white finish and minimalist styling complement contemporary and traditional kitchens alike. Built with durable Snaige components, this refrigerator is engineered for long-term performance and ease of maintenance.', 'price' => 549.99, 'sort_order' => 100, 'popularity_score' => 39, 'stock_left' => 2],
            ['slug' => 'miele-c3', 'category_slug' => 'home-appliances', 'brand' => 'Miele', 'name' => 'Complete C3 Vacuum', 'short_description' => 'Premium canister vacuum with a powerful Vortex Motor, HEPA AirClean filter, 4.5 L dust bag, 7.5 m cable, and 20-year build quality.', 'description' => 'The Miele Complete C3 is a premium canister vacuum cleaner that sets the standard for thorough, hygienic home cleaning. Its 890 W Miele-manufactured Vortex Motor generates powerful, consistent suction that lifts deep-seated dust, pet hair, and allergens from carpets, hard floors, and upholstery. The AirClean HEPA filter captures 99.95% of fine particles including dust mites and pollen, making it an ideal choice for allergy sufferers. A 7.5-metre cable radius and four smooth gliding castors allow effortless manoeuvrability around furniture and between rooms. The 4.5-litre dust bag extends the time between changes, and the integrated filter-change indicator reminds you when maintenance is needed. Miele builds the C3 to last for at least 20 years of regular use — a true long-term investment in a cleaner home.', 'price' => 399.99, 'sort_order' => 110, 'popularity_score' => 64, 'stock_left' => 7],
            ['slug' => 'apple-watch-6', 'category_slug' => 'smart-watches', 'brand' => 'Apple', 'name' => 'Watch Series 6', 'short_description' => 'Feature-rich smartwatch with blood oxygen sensor, ECG app, always-on Retina display, built-in GPS, Apple Pay, and WR50 water resistance.', 'description' => 'The Apple Watch Series 6 goes beyond timekeeping to become a comprehensive health and fitness companion worn on your wrist. The blood oxygen sensor and ECG app provide meaningful health insights you can share with your doctor, while the optical heart rate sensor tracks your heart rate continuously throughout the day. The always-on Retina LTPO OLED display stays visible in sunlight without requiring a wrist raise, and the S6 chip powers everything seamlessly. Built-in GPS tracks outdoor runs, rides, and hikes without your iPhone, and WR50 water resistance handles swimming sessions. With Apple Pay, Siri, and over 35,000 apps available on watchOS, the Series 6 is the most connected and capable wearable Apple has ever made.', 'price' => 299.99, 'sort_order' => 120, 'popularity_score' => 98, 'stock_left' => 6],
        ];

        Product::where('slug', 'motorola-razr-50')->delete();

        foreach ($products as $product) {
            $product['category_id'] = $categoryIds[$product['category_slug']] ?? null;
            unset($product['category_slug']);

            Product::updateOrCreate(
                ['slug' => $product['slug']],
                array_merge($product, ['is_active' => true])
            );
        }
    }
}
