<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class ProductImageSeeder extends Seeder
{
    public function run(): void
    {
        $images = [
            'Royal Professional Coffee Maker' => [
                'coffee-maker/saeco-royal-professional/image.png',
                'coffee-maker/saeco-royal-professional/image2.png',
                'coffee-maker/saeco-royal-professional/image3.png',
            ],
            'Surface Go 3' => [
                'laptop/microsoft-surface-go-3/image.png',
                'laptop/microsoft-surface-go-3/image2.png',
                'laptop/microsoft-surface-go-3/image3.png',
            ],
            'Microwave Oven' => [
                'microwave-oven/panasonic/image.png',
                'microwave-oven/panasonic/image1.png',
                'microwave-oven/panasonic/image2.png',
                'microwave-oven/panasonic/image3.png',
                'microwave-oven/panasonic/image4.png',
            ],
            'Wireless Mouse M510' => [
                'mouse/logitech-wireless-mouse-m510-black/image.png',
                'mouse/logitech-wireless-mouse-m510-black/image2.png',
                'mouse/logitech-wireless-mouse-m510-black/image3.png',
                'mouse/logitech-wireless-mouse-m510-black/image4.png',
            ],
            'iPhone 11' => [
                'phone/iphone-11/image.png',
                'phone/iphone-11/image2.png',
                'phone/iphone-11/image3.png',
                'phone/iphone-11/image4.png',
                'phone/iphone-11/image5.png',
                'phone/iphone-11/image6.png',
                'phone/iphone-11/image7.png',
            ],
            'Razr 50 Ultra' => [
                'phone/motorola-razr-50-ultra/image.png',
                'phone/motorola-razr-50-ultra/image2.png',
                'phone/motorola-razr-50-ultra/image3.png',
                'phone/motorola-razr-50-ultra/image4.png',
                'phone/motorola-razr-50-ultra/image5.png',
            ],
            'Moto G86' => [
                'phone/motorola-g86/image.png',
                'phone/motorola-g86/image2.png',
                'phone/motorola-g86/image3.png',
                'phone/motorola-g86/image4.png',
                'phone/motorola-g86/image5.png',
            ],
            'ZB2951 ErgoRapido' => [
                'vacuum-cleaner/electrolux-zb-2951-ergorapido/image.png',
                'vacuum-cleaner/electrolux-zb-2951-ergorapido/image2.png',
                'vacuum-cleaner/electrolux-zb-2951-ergorapido/image3.png',
                'vacuum-cleaner/electrolux-zb-2951-ergorapido/image4.png',
                'vacuum-cleaner/electrolux-zb-2951-ergorapido/image5.png',
            ],
            'Bosch Vacuum Cleaner' => [
                'vacuum-cleaner/bosch/image.png',
                'vacuum-cleaner/bosch/image1.png',
                'vacuum-cleaner/bosch/image2.png',
                'vacuum-cleaner/bosch/image3.png',
            ],
            'Bosch Serie 2 Vacuum' => [
                'vacuum-cleaner/miele-c3/image.png',
                'vacuum-cleaner/miele-c3/image2.png',
                'vacuum-cleaner/miele-c3/image3.png',
                'vacuum-cleaner/miele-c3/image4.png',
                'vacuum-cleaner/miele-c3/image5.png',
                'vacuum-cleaner/miele-c3/image6.png',
                'vacuum-cleaner/miele-c3/image7.png',
            ],
            'Bosch ProSilence Vacuum' => [
                'vacuum-cleaner/grunhelm-gvc8210g/image.png',
                'vacuum-cleaner/grunhelm-gvc8210g/image1.png',
                'vacuum-cleaner/grunhelm-gvc8210g/image2.png',
                'vacuum-cleaner/grunhelm-gvc8210g/image3.png',
                'vacuum-cleaner/grunhelm-gvc8210g/image4.png',
                'vacuum-cleaner/grunhelm-gvc8210g/image5.png',
            ],
            'Bosch Unlimited 7 Vacuum' => [
                'vacuum-cleaner/karcher-professional-nt/image.png',
                'vacuum-cleaner/karcher-professional-nt/image1.png',
                'vacuum-cleaner/karcher-professional-nt/image2.png',
                'vacuum-cleaner/karcher-professional-nt/image3.png',
            ],
            'Bosch Compacto Vacuum' => [
                'vacuum-cleaner/thomas-twin-tiger/image.png',
                'vacuum-cleaner/thomas-twin-tiger/image1.png',
                'vacuum-cleaner/thomas-twin-tiger/image2.png',
                'vacuum-cleaner/thomas-twin-tiger/image3.png',
                'vacuum-cleaner/thomas-twin-tiger/image4.png',
                'vacuum-cleaner/thomas-twin-tiger/image5.png',
            ],
            'Bosch AllergyCare Vacuum' => [
                'vacuum-cleaner/zelmer/image.png',
                'vacuum-cleaner/zelmer/image1.png',
                'vacuum-cleaner/zelmer/image2.png',
            ],
            'Electrolux Vacuum Cleaner' => [
                'vacuum-cleaner/electrolux/image.png',
                'vacuum-cleaner/electrolux/image1.png',
                'vacuum-cleaner/electrolux/image2.png',
                'vacuum-cleaner/electrolux/image3.png',
                'vacuum-cleaner/electrolux/image4.png',
                'vacuum-cleaner/electrolux/image5.png',
                'vacuum-cleaner/electrolux/image6.png',
                'vacuum-cleaner/electrolux/image7.png',
            ],
            'Electrolux Pure C9' => [
                'vacuum-cleaner/electrolux-zb-2951-ergorapido/image.png',
                'vacuum-cleaner/electrolux-zb-2951-ergorapido/image2.png',
                'vacuum-cleaner/electrolux-zb-2951-ergorapido/image3.png',
                'vacuum-cleaner/electrolux-zb-2951-ergorapido/image4.png',
                'vacuum-cleaner/electrolux-zb-2951-ergorapido/image5.png',
            ],
            'Electrolux UltraOne' => [
                'vacuum-cleaner/rowenta-swift-power/image.png',
                'vacuum-cleaner/rowenta-swift-power/image1.png',
                'vacuum-cleaner/rowenta-swift-power/image2.png',
                'vacuum-cleaner/rowenta-swift-power/image3.png',
            ],
            'Electrolux Well Q7' => [
                'vacuum-cleaner/rowenta-x-force-flex/image.png',
                'vacuum-cleaner/rowenta-x-force-flex/image1.png',
                'vacuum-cleaner/rowenta-x-force-flex/image2.png',
            ],
            'Electrolux Clean 600' => [
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image.png',
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image1.png',
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image2.png',
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image3.png',
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image4.png',
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image5.png',
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image6.png',
            ],
            'Rowenta Swift Power' => [
                'vacuum-cleaner/rowenta-swift-power/image.png',
                'vacuum-cleaner/rowenta-swift-power/image1.png',
                'vacuum-cleaner/rowenta-swift-power/image2.png',
                'vacuum-cleaner/rowenta-swift-power/image3.png',
            ],
            'X-Force Flex' => [
                'vacuum-cleaner/rowenta-x-force-flex/image.png',
                'vacuum-cleaner/rowenta-x-force-flex/image1.png',
                'vacuum-cleaner/rowenta-x-force-flex/image2.png',
            ],
            'X-Plorer Serie 75S' => [
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image.png',
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image1.png',
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image2.png',
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image3.png',
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image4.png',
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image5.png',
                'vacuum-cleaner/rowenta-x-plorer-serie-75s/image6.png',
            ],
            'Rowenta Silence Force' => [
                'vacuum-cleaner/roborock-s5-max/image.png',
                'vacuum-cleaner/roborock-s5-max/image1.png',
                'vacuum-cleaner/roborock-s5-max/image2.png',
                'vacuum-cleaner/roborock-s5-max/image3.png',
                'vacuum-cleaner/roborock-s5-max/image4.png',
                'vacuum-cleaner/roborock-s5-max/image5.png',
            ],
            'Rowenta Green Force' => [
                'vacuum-cleaner/xiaomi-vacuum-s20/image.png',
                'vacuum-cleaner/xiaomi-vacuum-s20/image1.png',
                'vacuum-cleaner/xiaomi-vacuum-s20/image2.png',
                'vacuum-cleaner/xiaomi-vacuum-s20/image3.png',
            ],
            'Rowenta Compact Power' => [
                'vacuum-cleaner/zoozee-z70/image.png',
                'vacuum-cleaner/zoozee-z70/image1.png',
                'vacuum-cleaner/zoozee-z70/image2.png',
                'vacuum-cleaner/zoozee-z70/image3.png',
                'vacuum-cleaner/zoozee-z70/image4.png',
                'vacuum-cleaner/zoozee-z70/image5.png',
                'vacuum-cleaner/zoozee-z70/image6.png',
                'vacuum-cleaner/zoozee-z70/8.png',
            ],
            'Power Bank 20000 mAh' => [
                'power-bank/20000-mah/image.png',
                'power-bank/20000-mah/image2.png',
                'power-bank/20000-mah/image3.png',
                'power-bank/20000-mah/image4.png',
                'power-bank/20000-mah/image5.png',
            ],
            'Refrigerator' => [
                'refrigerator/snaige/image.png',
                'refrigerator/snaige/image2.png',
                'refrigerator/snaige/image3.png',
                'refrigerator/snaige/image4.png',
                'refrigerator/snaige/image5.png',
                'refrigerator/snaige/image6.png',
            ],
            'Watch Series 6' => [
                'watch/apple-watch-6/image.png',
                'watch/apple-watch-6/image2.png',
                'watch/apple-watch-6/image3.png',
                'watch/apple-watch-6/image4.png',
                'watch/apple-watch-6/image5.png',
                'watch/apple-watch-6/image6.png',
            ],
            '8S3P Molicel Battery Pack' => [
                'accumulator/8s3p-molicel/image.png',
                'accumulator/8s3p-molicel/image1.png',
                'accumulator/8s3p-molicel/image2.png',
                'accumulator/8s3p-molicel/image3.png',
            ],
            'SE-G5.1 Pro-B Battery' => [
                'accumulator/deye-se-g5-1-pro-b/image.png',
                'accumulator/deye-se-g5-1-pro-b/image1.png',
                'accumulator/deye-se-g5-1-pro-b/image2.png',
                'accumulator/deye-se-g5-1-pro-b/image3.png',
                'accumulator/deye-se-g5-1-pro-b/image4.png',
            ],
            'Langzeit Battery Pack' => [
                'accumulator/langzeit/image.png',
                'accumulator/langzeit/image1.png',
                'accumulator/langzeit/image2.png',
                'accumulator/langzeit/image3.png',
                'accumulator/langzeit/image4.png',
                'accumulator/langzeit/image5.png',
                'accumulator/langzeit/image6.png',
            ],
            'USB 2.0 Cable' => [
                'cable/usb-2-0/image.png',
                'cable/usb-2-0/image1.png',
                'cable/usb-2-0/image2.png',
                'cable/usb-2-0/image3.png',
                'cable/usb-2-0/image4.png',
            ],
            'HERO7 Black' => [
                'camera/gopro-hero-7/image.png',
                'camera/gopro-hero-7/image1.png',
                'camera/gopro-hero-7/image2.png',
                'camera/gopro-hero-7/image3.png',
                'camera/gopro-hero-7/image4.png',
                'camera/gopro-hero-7/image5.png',
                'camera/gopro-hero-7/image6.png',
            ],
            'HERO11 Black' => [
                'camera/gopro-hero-11/image.png',
                'camera/gopro-hero-11/image1.png',
                'camera/gopro-hero-11/image2.png',
                'camera/gopro-hero-11/image3.png',
                'camera/gopro-hero-11/image4.png',
                'camera/gopro-hero-11/image5.png',
                'camera/gopro-hero-11/image6.png',
            ],
            'HERO13 Black' => [
                'camera/gopro-hero-13/image.png',
                'camera/gopro-hero-13/image1.png',
                'camera/gopro-hero-13/image2.png',
                'camera/gopro-hero-13/image3.png',
                'camera/gopro-hero-13/image4.png',
                'camera/gopro-hero-13/image5.png',
                'camera/gopro-hero-13/image6.png',
            ],
            'HERO 2018' => [
                'camera/gopro-hero-2018/image.png',
                'camera/gopro-hero-2018/image1.png',
                'camera/gopro-hero-2018/image2.png',
                'camera/gopro-hero-2018/image3.png',
                'camera/gopro-hero-2018/image4.png',
                'camera/gopro-hero-2018/image5.png',
                'camera/gopro-hero-2018/image6.png',
            ],
            'HERO7 Silver' => [
                'camera/gopro7/image.png',
                'camera/gopro7/image1.png',
                'camera/gopro7/image2.png',
            ],
            'HERO11 Mini' => [
                'camera/go-pro-11/image.png',
                'camera/go-pro-11/image1.png',
                'camera/go-pro-11/image2.png',
                'camera/go-pro-11/image3.png',
                'camera/go-pro-11/image4.png',
                'camera/go-pro-11/image5.png',
                'camera/go-pro-11/image6.png',
            ],
            'ZV-E10' => [
                'camera/sony-zv-e10/image.png',
                'camera/sony-zv-e10/image1.png',
                'camera/sony-zv-e10/image2.png',
                'camera/sony-zv-e10/image3.png',
                'camera/sony-zv-e10/image4.png',
                'camera/sony-zv-e10/image5.png',
            ],
            'NEX-5N' => [
                'camera/sony-nex5-n/image.png',
                'camera/sony-nex5-n/image1.png',
                'camera/sony-nex5-n/image2.png',
                'camera/sony-nex5-n/image3.png',
                'camera/sony-nex5-n/image4.png',
                'camera/sony-nex5-n/image5.png',
                'camera/sony-nex5-n/image6.png',
            ],
            'Cyber-shot DSC-W55' => [
                'camera/sony-cyber-shot-dsc-w55/image.png',
                'camera/sony-cyber-shot-dsc-w55/image1.png',
                'camera/sony-cyber-shot-dsc-w55/image2.png',
                'camera/sony-cyber-shot-dsc-w55/image3.png',
                'camera/sony-cyber-shot-dsc-w55/image4.png',
            ],
            'Alpha A6000' => [
                'camera/icsee/image.png',
                'camera/icsee/image1.png',
                'camera/icsee/image2.png',
            ],
            'Alpha A7 III' => [
                'camera/lafoch-y403/image.png',
                'camera/lafoch-y403/image1.png',
                'camera/lafoch-y403/image2.png',
                'camera/lafoch-y403/image3.png',
            ],
            'Cyber-shot RX100' => [
                'camera/szsinocam/image.png',
                'camera/szsinocam/image1.png',
                'camera/szsinocam/image2.png',
                'camera/szsinocam/image3.png',
                'camera/szsinocam/image4.png',
                'camera/szsinocam/image5.png',
                'camera/szsinocam/image6.png',
            ],
            'EOS R100' => [
                'camera/canon-r100/image.png',
                'camera/canon-r100/image1.png',
                'camera/canon-r100/image2.png',
                'camera/canon-r100/image3.png',
                'camera/canon-r100/image4.png',
                'camera/canon-r100/image5.png',
                'camera/canon-r100/image6.png',
                'camera/canon-r100/image7.png',
            ],
            'EOS R50' => [
                'camera/dji-osmo-pocket-3-standard/image.png',
                'camera/dji-osmo-pocket-3-standard/image1.png',
                'camera/dji-osmo-pocket-3-standard/image2.png',
                'camera/dji-osmo-pocket-3-standard/image3.png',
                'camera/dji-osmo-pocket-3-standard/image4.png',
                'camera/dji-osmo-pocket-3-standard/image5.png',
                'camera/dji-osmo-pocket-3-standard/image6.png',
            ],
            'PowerShot G7 X Mark III' => [
                'camera/insta360-x5/image.png',
                'camera/insta360-x5/image1.png',
                'camera/insta360-x5/image2.png',
                'camera/insta360-x5/image3.png',
            ],
            'EOS M50 Mark II' => [
                'camera/samsung-dv150f/image.png',
                'camera/samsung-dv150f/image1.png',
                'camera/samsung-dv150f/image2.png',
                'camera/samsung-dv150f/image3.png',
                'camera/samsung-dv150f/image4.png',
                'camera/samsung-dv150f/image5.png',
                'camera/samsung-dv150f/image6.png',
                'camera/samsung-dv150f/image7.png',
            ],
            'EOS 90D' => [
                'camera/logitech-hd-720/image.png',
                'camera/logitech-hd-720/image1.png',
                'camera/logitech-hd-720/image2.png',
            ],
            'EOS R8' => [
                'camera/vb603/image.png',
                'camera/vb603/image1.png',
                'camera/vb603/image2.png',
                'camera/vb603/image3.png',
                'camera/vb603/image4.png',
                'camera/vb603/image5.png',
            ],
            'Air Conditioner' => [
                'conditioner/osaka/image.png',
                'conditioner/osaka/image1.png',
                'conditioner/osaka/image2.png',
                'conditioner/osaka/image3.png',
            ],
            'Studio Display' => [
                'display/apple-studio-display/image.png',
                'display/apple-studio-display/image1.png',
                'display/apple-studio-display/image2.png',
                'display/apple-studio-display/image3.png',
                'display/apple-studio-display/image4.png',
                'display/apple-studio-display/image5.png',
                'display/apple-studio-display/image6.png',
                'display/apple-studio-display/image7.png',
            ],
            'AirPods 3' => [
                'earphone/air-pods-3/image.png',
                'earphone/air-pods-3/image1.png',
                'earphone/air-pods-3/image2.png',
                'earphone/air-pods-3/image3.png',
                'earphone/air-pods-3/image4.png',
                'earphone/air-pods-3/image5.png',
            ],
            'JLab Earbuds' => [
                'earphone/jlab/image.png',
                'earphone/jlab/image1.png',
                'earphone/jlab/image2.png',
                'earphone/jlab/image3.png',
                'earphone/jlab/image4.png',
                'earphone/jlab/image5.png',
            ],
            'PlayStation 4 Fat' => [
                'playstation/playstation-4-fat/image.png',
                'playstation/playstation-4-fat/image1.png',
                'playstation/playstation-4-fat/image2.png',
                'playstation/playstation-4-fat/image3.png',
                'playstation/playstation-4-fat/image4.png',
                'playstation/playstation-4-fat/image5.png',
            ],
            'PlayStation 4 Pro' => [
                'playstation/playstation-4-pro/image.png',
                'playstation/playstation-4-pro/image1.png',
                'playstation/playstation-4-pro/image2.png',
                'playstation/playstation-4-pro/image3.png',
                'playstation/playstation-4-pro/image4.png',
                'playstation/playstation-4-pro/image5.png',
                'playstation/playstation-4-pro/image6.png',
            ],
            'Silent Pro M2 Power Supply' => [
                'power-supply/cooler-master-silent-pro-m2/image.png',
                'power-supply/cooler-master-silent-pro-m2/image1.png',
                'power-supply/cooler-master-silent-pro-m2/image2.png',
                'power-supply/cooler-master-silent-pro-m2/image3.png',
                'power-supply/cooler-master-silent-pro-m2/image4.png',
                'power-supply/cooler-master-silent-pro-m2/image5.png',
                'power-supply/cooler-master-silent-pro-m2/image6.png',
                'power-supply/cooler-master-silent-pro-m2/image7.png',
            ],
            'Cobra Power Supply' => [
                'power-supply/raidmax-cobra/image.png',
                'power-supply/raidmax-cobra/image1.png',
                'power-supply/raidmax-cobra/image2.png',
                'power-supply/raidmax-cobra/image3.png',
                'power-supply/raidmax-cobra/image4.png',
                'power-supply/raidmax-cobra/image5.png',
                'power-supply/raidmax-cobra/image6.png',
                'power-supply/raidmax-cobra/image7.png',
            ],
            'Bang SE' => [
                'speaker/transmart-bang-se/image.png',
                'speaker/transmart-bang-se/image1.png',
                'speaker/transmart-bang-se/image2.png',
                'speaker/transmart-bang-se/image3.png',
                'speaker/transmart-bang-se/image4.png',
                'speaker/transmart-bang-se/image5.png',
                'speaker/transmart-bang-se/image6.png',
                'speaker/transmart-bang-se/image7.png',
            ],
            'iPad 4' => [
                'tablet/apple-ipad-4/image.png',
                'tablet/apple-ipad-4/image1.png',
                'tablet/apple-ipad-4/image2.png',
            ],
            'iPad 5' => [
                'tablet/ipad-5/image.png',
                'tablet/ipad-5/image1.png',
                'tablet/ipad-5/image2.png',
                'tablet/ipad-5/image3.png',
                'tablet/ipad-5/image4.png',
                'tablet/ipad-5/image5.png',
                'tablet/ipad-5/image6.png',
                'tablet/ipad-5/image7.png',
            ],
            'iPad 7' => [
                'tablet/ipad-7/image.png',
                'tablet/ipad-7/image1.png',
                'tablet/ipad-7/image2.png',
                'tablet/ipad-7/image3.png',
                'tablet/ipad-7/image4.png',
                'tablet/ipad-7/image5.png',
                'tablet/ipad-7/image6.png',
                'tablet/ipad-7/image7.png',
            ],
            'iPad 8th Generation' => [
                'tablet/ipad-8th-generation/image.png',
                'tablet/ipad-8th-generation/image1.png',
                'tablet/ipad-8th-generation/image2.png',
                'tablet/ipad-8th-generation/image3.png',
                'tablet/ipad-8th-generation/image4.png',
                'tablet/ipad-8th-generation/image5.png',
            ],
            'iPad 9' => [
                'tablet/ipad-9/image.png',
                'tablet/ipad-9/image1.png',
                'tablet/ipad-9/image2.png',
                'tablet/ipad-9/image3.png',
                'tablet/ipad-9/image4.png',
                'tablet/ipad-9/image5.png',
            ],
            'iPad 11 A16' => [
                'tablet/ipad-11-a16/image.png',
                'tablet/ipad-11-a16/image1.png',
                'tablet/ipad-11-a16/image2.png',
                'tablet/ipad-11-a16/image3.png',
                'tablet/ipad-11-a16/image4.png',
            ],
            'Galaxy Tab A' => [
                'tablet/samsung-galaxy-tab-a/image.png',
                'tablet/samsung-galaxy-tab-a/image1.png',
                'tablet/samsung-galaxy-tab-a/image2.png',
                'tablet/samsung-galaxy-tab-a/image3.png',
            ],
            'Samsung 10' => [
                'tablet/samsung-10/image.png',
                'tablet/samsung-10/image1.png',
                'tablet/samsung-10/image2.png',
                'tablet/samsung-10/image3.png',
                'tablet/samsung-10/image4.png',
                'tablet/samsung-10/image5.png',
                'tablet/samsung-10/image6.png',
                'tablet/samsung-10/image7.png',
            ],
            'Galaxy Tab A8' => [
                'tablet/samsung-tab-a8/image.png',
                'tablet/samsung-tab-a8/image1.png',
                'tablet/samsung-tab-a8/image2.png',
                'tablet/samsung-tab-a8/image3.png',
                'tablet/samsung-tab-a8/image4.png',
                'tablet/samsung-tab-a8/image5.png',
                'tablet/samsung-tab-a8/image6.png',
            ],
            'Galaxy Tab A9' => [
                'tablet/samsung-galaxy-tab-a9/image.png',
                'tablet/samsung-galaxy-tab-a9/image1.png',
                'tablet/samsung-galaxy-tab-a9/image2.png',
                'tablet/samsung-galaxy-tab-a9/image3.png',
                'tablet/samsung-galaxy-tab-a9/image4.png',
            ],
            'Galaxy Tab S11' => [
                'tablet/samsung-galaxy-tab-s11/image.png',
                'tablet/samsung-galaxy-tab-s11/image1.png',
                'tablet/samsung-galaxy-tab-s11/image2.png',
                'tablet/samsung-galaxy-tab-s11/image3.png',
                'tablet/samsung-galaxy-tab-s11/image4.png',
                'tablet/samsung-galaxy-tab-s11/image5.png',
                'tablet/samsung-galaxy-tab-s11/image6.png',
            ],
            'Galaxy Tab S10 Ultra' => [
                'tablet/samsung-galaxy-tab-s10-ultra/image.png',
                'tablet/samsung-galaxy-tab-s10-ultra/image1.png',
                'tablet/samsung-galaxy-tab-s10-ultra/image2.png',
                'tablet/samsung-galaxy-tab-s10-ultra/image3.png',
            ],
            'Tab 4' => [
                'tablet/lenovo-tab-4/image.png',
                'tablet/lenovo-tab-4/image1.png',
                'tablet/lenovo-tab-4/image2.png',
                'tablet/lenovo-tab-4/image3.png',
                'tablet/lenovo-tab-4/image4.png',
                'tablet/lenovo-tab-4/image5.png',
                'tablet/lenovo-tab-4/image6.png',
                'tablet/lenovo-tab-4/image7.png',
            ],
            'Tab M8' => [
                'tablet/lenovo-tab-m8/image.png',
                'tablet/lenovo-tab-m8/image1.png',
                'tablet/lenovo-tab-m8/image2.png',
                'tablet/lenovo-tab-m8/image3.png',
                'tablet/lenovo-tab-m8/image4.png',
                'tablet/lenovo-tab-m8/image5.png',
                'tablet/lenovo-tab-m8/image6.png',
            ],
            'Tab M10' => [
                'tablet/lenovo-tab-m10/image.png',
                'tablet/lenovo-tab-m10/image1.png',
                'tablet/lenovo-tab-m10/image2.png',
            ],
            'Tab P11' => [
                'tablet/lenovo-tab-p11/image.png',
                'tablet/lenovo-tab-p11/image1.png',
                'tablet/lenovo-tab-p11/image2.png',
                'tablet/lenovo-tab-p11/image3.png',
                'tablet/lenovo-tab-p11/image4.png',
                'tablet/lenovo-tab-p11/image5.png',
                'tablet/lenovo-tab-p11/image6.png',
                'tablet/lenovo-tab-p11/image7.png',
            ],
            'P11 2nd Gen' => [
                'tablet/lenovo-p11-2nd-gen/image.png',
                'tablet/lenovo-p11-2nd-gen/image1.png',
                'tablet/lenovo-p11-2nd-gen/image2.png',
                'tablet/lenovo-p11-2nd-gen/image3.png',
                'tablet/lenovo-p11-2nd-gen/image4.png',
                'tablet/lenovo-p11-2nd-gen/image5.png',
                'tablet/lenovo-p11-2nd-gen/image6.png',
            ],
            'TB3-71IO' => [
                'tablet/lenovo-tb3-71io/image.png',
                'tablet/lenovo-tb3-71io/image1.png',
                'tablet/lenovo-tb3-71io/image2.png',
                'tablet/lenovo-tb3-71io/image3.png',
                'tablet/lenovo-tb3-71io/image4.png',
            ],
            'Intuos Pro Large' => [
                'tablet/wacom-intuos-pro-large/image.png',
                'tablet/wacom-intuos-pro-large/image1.png',
                'tablet/wacom-intuos-pro-large/image2.png',
                'tablet/wacom-intuos-pro-large/image3.png',
                'tablet/wacom-intuos-pro-large/image4.png',
                'tablet/wacom-intuos-pro-large/image5.png',
                'tablet/wacom-intuos-pro-large/image6.png',
                'tablet/wacom-intuos-pro-large/image7.png',
            ],
            'WAN282ECO' => [
                'washing-machine/bosch-wan282eco/image.png',
                'washing-machine/bosch-wan282eco/image1.png',
                'washing-machine/bosch-wan282eco/image2.png',
                'washing-machine/bosch-wan282eco/image3.png',
                'washing-machine/bosch-wan282eco/image4.png',
                'washing-machine/bosch-wan282eco/image5.png',
                'washing-machine/bosch-wan282eco/image6.png',
                'washing-machine/bosch-wan282eco/image7.png',
            ],
            'Washing Machine' => [
                'washing-machine/indesit/image.png',
                'washing-machine/indesit/image1.png',
                'washing-machine/indesit/image2.png',
            ],
            'ZWT5105' => [
                'washing-machine/zanussi-zwt5105/image.png',
                'washing-machine/zanussi-zwt5105/image1.png',
                'washing-machine/zanussi-zwt5105/image2.png',
            ],
            'Linea Mini' => [
                'coffee-maker/la-marzocco-fb80/image.png',
                'coffee-maker/la-marzocco-fb80/image1.png',
                'coffee-maker/la-marzocco-fb80/image2.png',
                'coffee-maker/la-marzocco-fb80/image3.png',
                'coffee-maker/la-marzocco-fb80/image4.png',
                'coffee-maker/la-marzocco-fb80/image5.png',
                'coffee-maker/la-marzocco-fb80/image6.png',
                'coffee-maker/la-marzocco-fb80/image7.png',
            ],
            'PC-KA 1191' => [
                'coffee-maker/profi-cook-pc-ka-1191/image.png',
                'coffee-maker/profi-cook-pc-ka-1191/image1.png',
                'coffee-maker/profi-cook-pc-ka-1191/image2.png',
                'coffee-maker/profi-cook-pc-ka-1191/image3.png',
                'coffee-maker/profi-cook-pc-ka-1191/image4.png',
            ],
            'ROG Zephyrus G15' => [
                'laptop/asus-rog-zephyrus-g15/image.png',
                'laptop/asus-rog-zephyrus-g15/image1.png',
                'laptop/asus-rog-zephyrus-g15/image2.png',
                'laptop/asus-rog-zephyrus-g15/image3.png',
                'laptop/asus-rog-zephyrus-g15/image4.png',
            ],
            'Ryzen 5 Laptop' => [
                'laptop/hp-ryzen-5/image.png',
                'laptop/hp-ryzen-5/image1.png',
                'laptop/hp-ryzen-5/image2.png',
                'laptop/hp-ryzen-5/image3.png',
            ],
            'ThinkPad T14s Gen 2' => [
                'laptop/lenovo-thinkpad-t14s-gen-2/image.png',
                'laptop/lenovo-thinkpad-t14s-gen-2/image1.png',
                'laptop/lenovo-thinkpad-t14s-gen-2/image2.png',
                'laptop/lenovo-thinkpad-t14s-gen-2/image3.png',
                'laptop/lenovo-thinkpad-t14s-gen-2/image4.png',
                'laptop/lenovo-thinkpad-t14s-gen-2/image5.png',
                'laptop/lenovo-thinkpad-t14s-gen-2/image6.png',
                'laptop/lenovo-thinkpad-t14s-gen-2/image7.png',
            ],
            'MacBook Pro 15' => [
                'laptop/macbook-pro-15/image.png',
                'laptop/macbook-pro-15/image1.png',
                'laptop/macbook-pro-15/image2.png',
                'laptop/macbook-pro-15/image3.png',
                'laptop/macbook-pro-15/image4.png',
                'laptop/macbook-pro-15/image5.png',
                'laptop/macbook-pro-15/image6.png',
                'laptop/macbook-pro-15/image7.png',
            ],
            'Apple MacBook Air 13' => [
                'laptop/apple-macbook-air-13/image.png',
                'laptop/apple-macbook-air-13/image1.png',
                'laptop/apple-macbook-air-13/image2.png',
            ],
            'Apple MacBook Pro 13' => [
                'laptop/apple-macbook-pro-13/image.png',
                'laptop/apple-macbook-pro-13/image1.png',
                'laptop/apple-macbook-pro-13/image2.png',
                'laptop/apple-macbook-pro-13/image3.png',
                'laptop/apple-macbook-pro-13/image4.png',
                'laptop/apple-macbook-pro-13/image5.png',
            ],
            'ASUS Laptop 2017' => [
                'laptop/asus-2017/image.png',
                'laptop/asus-2017/image1.png',
                'laptop/asus-2017/image2.png',
            ],
            'ASUS TUF FX505DT-BQ143' => [
                'laptop/asus-tuf-fx505dt-bq143/image.png',
                'laptop/asus-tuf-fx505dt-bq143/image1.png',
                'laptop/asus-tuf-fx505dt-bq143/image2.png',
                'laptop/asus-tuf-fx505dt-bq143/image3.png',
                'laptop/asus-tuf-fx505dt-bq143/image4.png',
                'laptop/asus-tuf-fx505dt-bq143/image5.png',
                'laptop/asus-tuf-fx505dt-bq143/image6.png',
            ],
            'ASUS X501A' => [
                'laptop/asus-x501a/image.png',
                'laptop/asus-x501a/image1.png',
                'laptop/asus-x501a/image2.png',
            ],
            'ASUS X551M' => [
                'laptop/asus-x551m/image.png',
                'laptop/asus-x551m/image1.png',
                'laptop/asus-x551m/image2.png',
                'laptop/asus-x551m/image3.png',
            ],
            'ASUS X553CA' => [
                'laptop/asus-x553ca/image.png',
                'laptop/asus-x553ca/image1.png',
                'laptop/asus-x553ca/image2.png',
                'laptop/asus-x553ca/image3.png',
                'laptop/asus-x553ca/image4.png',
                'laptop/asus-x553ca/image5.png',
                'laptop/asus-x553ca/image6.png',
            ],
            'Lenovo G565' => [
                'laptop/lenovo-g-565/image.png',
                'laptop/lenovo-g-565/image1.png',
                'laptop/lenovo-g-565/image2.png',
                'laptop/lenovo-g-565/image3.png',
                'laptop/lenovo-g-565/image4.png',
            ],
            'Lenovo Gaming 3' => [
                'laptop/lenovo-gaming-3/image.png',
                'laptop/lenovo-gaming-3/image1.png',
                'laptop/lenovo-gaming-3/image2.png',
            ],
            'Lenovo IdeaPad 330' => [
                'laptop/lenovo-ideapad-330/image.png',
                'laptop/lenovo-ideapad-330/image1.png',
                'laptop/lenovo-ideapad-330/image2.png',
                'laptop/lenovo-ideapad-330/image3.png',
            ],
            'Lenovo S206' => [
                'laptop/lenovo-s-206/image.png',
                'laptop/lenovo-s-206/image1.png',
                'laptop/lenovo-s-206/image2.png',
                'laptop/lenovo-s-206/image3.png',
                'laptop/lenovo-s-206/image4.png',
                'laptop/lenovo-s-206/image5.png',
                'laptop/lenovo-s-206/image6.png',
            ],
            'ThinkPad T490' => [
                'laptop/lenovo-thinkpad-t490/image.png',
                'laptop/lenovo-thinkpad-t490/image1.png',
                'laptop/lenovo-thinkpad-t490/image2.png',
                'laptop/lenovo-thinkpad-t490/image3.png',
                'laptop/lenovo-thinkpad-t490/image4.png',
                'laptop/lenovo-thinkpad-t490/image5.png',
                'laptop/lenovo-thinkpad-t490/image6.png',
                'laptop/lenovo-thinkpad-t490/image7.png',
            ],
            'MacBook A1286' => [
                'laptop/macbook-a1286/image.png',
                'laptop/macbook-a1286/image1.png',
                'laptop/macbook-a1286/image2.png',
                'laptop/macbook-a1286/image3.png',
                'laptop/macbook-a1286/image4.png',
                'laptop/macbook-a1286/image5.png',
                'laptop/macbook-a1286/image6.png',
                'laptop/macbook-a1286/image7.png',
            ],
            'MacBook Air 13 (Legacy)' => [
                'laptop/macbook-air-13/image.png',
                'laptop/macbook-air-13/image1.png',
                'laptop/macbook-air-13/image2.png',
                'laptop/macbook-air-13/image3.png',
                'laptop/macbook-air-13/image4.png',
                'laptop/macbook-air-13/image5.png',
                'laptop/macbook-air-13/image6.png',
            ],
            'MacBook Pro 13 Touch Bar' => [
                'laptop/macbook-pro-13-touh-bar/image.png',
                'laptop/macbook-pro-13-touh-bar/image1.png',
                'laptop/macbook-pro-13-touh-bar/image2.png',
                'laptop/macbook-pro-13-touh-bar/image3.png',
                'laptop/macbook-pro-13-touh-bar/image4.png',
                'laptop/macbook-pro-13-touh-bar/image5.png',
                'laptop/macbook-pro-13-touh-bar/image6.png',
                'laptop/macbook-pro-13-touh-bar/image7.png',
            ],
            'iPhone 11 Pro Max' => [
                'phone/iphone-11-pro-max/image.png',
                'phone/iphone-11-pro-max/image1.png',
                'phone/iphone-11-pro-max/image2.png',
                'phone/iphone-11-pro-max/image3.png',
                'phone/iphone-11-pro-max/image4.png',
                'phone/iphone-11-pro-max/image5.png',
                'phone/iphone-11-pro-max/image6.png',
                'phone/iphone-11-pro-max/image7.png',
            ],
            'iPhone 12' => [
                'phone/iphone-12/image.png',
                'phone/iphone-12/image1.png',
                'phone/iphone-12/image2.png',
                'phone/iphone-12/image3.png',
                'phone/iphone-12/image4.png',
                'phone/iphone-12/image5.png',
                'phone/iphone-12/image6.png',
                'phone/iphone-12/image7.png',
            ],
            'iPhone 13' => [
                'phone/iphone-13/image.png',
                'phone/iphone-13/image1.png',
                'phone/iphone-13/image2.png',
                'phone/iphone-13/image3.png',
                'phone/iphone-13/image4.png',
                'phone/iphone-13/image5.png',
                'phone/iphone-13/image6.png',
            ],
            'iPhone 15 Pro' => [
                'phone/iphone-15-pro/image.png',
                'phone/iphone-15-pro/image1.png',
                'phone/iphone-15-pro/image2.png',
                'phone/iphone-15-pro/image3.png',
                'phone/iphone-15-pro/image4.png',
                'phone/iphone-15-pro/image5.png',
                'phone/iphone-15-pro/image6.png',
            ],
            'iPhone 16 Pro' => [
                'phone/iphone-16-pro/image.png',
                'phone/iphone-16-pro/image1.png',
                'phone/iphone-16-pro/image2.png',
                'phone/iphone-16-pro/image3.png',
                'phone/iphone-16-pro/image4.png',
                'phone/iphone-16-pro/image5.png',
            ],
            'iPhone 7 Plus' => [
                'phone/iphone-7-plus/image.png',
                'phone/iphone-7-plus/image1.png',
                'phone/iphone-7-plus/image2.png',
                'phone/iphone-7-plus/image3.png',
                'phone/iphone-7-plus/image4.png',
                'phone/iphone-7-plus/image5.png',
            ],
            'iPhone X' => [
                'phone/iphone-x/image.png',
                'phone/iphone-x/image1.png',
                'phone/iphone-x/image2.png',
                'phone/iphone-x/image3.png',
                'phone/iphone-x/image4.png',
                'phone/iphone-x/image5.png',
            ],
            'GM 8 Go' => [
                'phone/general-mobile-gm-8-go/image.png',
                'phone/general-mobile-gm-8-go/image1.png',
                'phone/general-mobile-gm-8-go/image2.png',
            ],
            'Galaxy M22' => [
                'phone/samsung-galaxy-m22/image.png',
                'phone/samsung-galaxy-m22/image1.png',
                'phone/samsung-galaxy-m22/image2.png',
                'phone/samsung-galaxy-m22/image3.png',
                'phone/samsung-galaxy-m22/image4.png',
                'phone/samsung-galaxy-m22/image5.png',
            ],
            'Galaxy S23 FE' => [
                'phone/samsung-galaxy-s23fe/image.png',
                'phone/samsung-galaxy-s23fe/image1.png',
                'phone/samsung-galaxy-s23fe/image2.png',
                'phone/samsung-galaxy-s23fe/image3.png',
                'phone/samsung-galaxy-s23fe/image4.png',
                'phone/samsung-galaxy-s23fe/image5.png',
                'phone/samsung-galaxy-s23fe/image6.png',
            ],
            'Galaxy S24' => [
                'phone/samsung-s24/image.png',
                'phone/samsung-s24/image1.png',
                'phone/samsung-s24/image2.png',
                'phone/samsung-s24/image3.png',
                'phone/samsung-s24/image4.png',
                'phone/samsung-s24/image5.png',
                'phone/samsung-s24/image6.png',
            ],
            'Galaxy Z Fold' => [
                'phone/samsung-z-fold/image.png',
                'phone/samsung-z-fold/image1.png',
                'phone/samsung-z-fold/image2.png',
                'phone/samsung-z-fold/image3.png',
            ],
            'Xperia XA2 Ultra' => [
                'phone/sony-xperia-xa-2-ultra/image.png',
                'phone/sony-xperia-xa-2-ultra/image1.png',
                'phone/sony-xperia-xa-2-ultra/image2.png',
                'phone/sony-xperia-xa-2-ultra/image3.png',
                'phone/sony-xperia-xa-2-ultra/image4.png',
                'phone/sony-xperia-xa-2-ultra/image5.png',
                'phone/sony-xperia-xa-2-ultra/image6.png',
                'phone/sony-xperia-xa-2-ultra/image7.png',
            ],
            'Redmi A5' => [
                'phone/xiaomi-redmi-a5/image.png',
                'phone/xiaomi-redmi-a5/image1.png',
                'phone/xiaomi-redmi-a5/image2.png',
                'phone/xiaomi-redmi-a5/image3.png',
                'phone/xiaomi-redmi-a5/image4.png',
                'phone/xiaomi-redmi-a5/image5.png',
                'phone/xiaomi-redmi-a5/image6.png',
            ],
            'Redmi 9A' => [
                'phone/redmi-9a/image.png',
                'phone/redmi-9a/image1.png',
                'phone/redmi-9a/image2.png',
                'phone/redmi-9a/image3.png',
            ],
            'Redmi Note 13' => [
                'phone/redmi-note-13/image.png',
                'phone/redmi-note-13/image1.png',
                'phone/redmi-note-13/image2.png',
            ],
            'Redmi Note 8T' => [
                'phone/redmi-note-8t/image.png',
                'phone/redmi-note-8t/image1.png',
                'phone/redmi-note-8t/image2.png',
                'phone/redmi-note-8t/image3.png',
                'phone/redmi-note-8t/image4.png',
                'phone/redmi-note-8t/image5.png',
            ],
            'Galaxy A52' => [
                'phone/samsung-galaxy-a52/image.png',
                'phone/samsung-galaxy-a52/image1.png',
                'phone/samsung-galaxy-a52/image2.png',
                'phone/samsung-galaxy-a52/image3.png',
                'phone/samsung-galaxy-a52/image4.png',
                'phone/samsung-galaxy-a52/image5.png',
                'phone/samsung-galaxy-a52/image6.png',
                'phone/samsung-galaxy-a52/image7.png',
            ],
            'Galaxy S21' => [
                'phone/samsung-s21/image.png',
                'phone/samsung-s21/image1.png',
                'phone/samsung-s21/image2.png',
                'phone/samsung-s21/image3.png',
                'phone/samsung-s21/image4.png',
                'phone/samsung-s21/image5.png',
                'phone/samsung-s21/image6.png',
            ],
            'Xiaomi 11T' => [
                'phone/xiaomi-11t/image.png',
                'phone/xiaomi-11t/image1.png',
                'phone/xiaomi-11t/image2.png',
                'phone/xiaomi-11t/image3.png',
                'phone/xiaomi-11t/image4.png',
            ],
            'Xiaomi Redmi 9' => [
                'phone/xiaomi-redmi-9/image.png',
                'phone/xiaomi-redmi-9/image1.png',
                'phone/xiaomi-redmi-9/image2.png',
                'phone/xiaomi-redmi-9/image3.png',
                'phone/xiaomi-redmi-9/image4.png',
                'phone/xiaomi-redmi-9/image5.png',
            ],
            'Vivoactive 6' => [
                'watch/garmin-vivoactive-6/image.png',
                'watch/garmin-vivoactive-6/image1.png',
                'watch/garmin-vivoactive-6/image2.png',
                'watch/garmin-vivoactive-6/image3.png',
            ],
        ];

        $productIds = Product::query()->pluck('id', 'name');

        foreach ($images as $name => $urls) {
            $productId = $productIds[$name] ?? null;

            if ($productId === null) {
                continue;
            }

            ProductImage::where('product_id', $productId)->delete();

            foreach ($urls as $position => $url) {
                ProductImage::updateOrCreate(
                    ['product_id' => $productId, 'position' => $position + 1],
                    ['url' => $url]
                );
            }
        }
    }
}
